language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

script:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - chmod +x coveralls.phar
  - phpunit -c phpunit.xml
  - php coveralls.phar -v -x build/logs/clover.xml